# Generated by Django 2.2 on 2019-04-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creatorz', '0002_customer_playback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('remote_url', models.TextField()),
                ('playback', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='play_errors', to='creatorz.Playback')),
            ],
        ),
    ]
